services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: vollAPI
    volumes:
      - ./sqlData:/var/lib/pg
    ports:
      - '3306:3306'